name: Automated Image Processing CI

on:
  push:
    branches:
      - main
      - feature/initial
      - feature/image-processing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Image Processing
      run: python project/src/main.py

    - name: Check output folder
      run: |
        if [ -d "output" ]; then
          echo "Output folder exists"
        else
          echo "Output folder missing" && exit 1
        fi
